server:
  port: 9009
spring:
  jpa:
    properties.hibernate.dialect : org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate.ddl-auto: validate
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/hospital
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    enabled: true
  sql:
    init:
      mode: always
      continue-on-error: false

