name: Workflow for Test Cases

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v2

      - name: Set up JDK 8 and Cache dependencies
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: adopt
          cache: maven

      - name: Build project with Maven
        run: mvn -B package --file pom.xml